<<<<<<< HEAD
=======
server:
  port: 0

>>>>>>> master
app:
  kafka:
    enabled: true

spring:
  kafka:
    producer:
      bootstrap-servers:
        - localhost:9092
<<<<<<< HEAD
=======
        

      key-serializer: org.apache.kafka.common.serialization.StringSerializer

      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    admin:
      fail-fast: false
      auto-create: false
>>>>>>> master
