server:
  port: 0

app:
  kafka:
<<<<<<< HEAD
    enabled: false

spring:
  kafka:
    admin:
      fail-fast: false
      auto-create: false

    producer:
      bootstrap-servers:
        - localhost:9092


      key-serializer: org.apache.kafka.common.serialization.StringSerializer

      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
=======
    enabled: false
>>>>>>> master
